apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: voom-user-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/execution-environment: gen2
    spec:
      serviceAccountName: voom-sa@PROJECT_ID.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: europe-west1-docker.pkg.dev/PROJECT_ID/voom-repo/voom-user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'firestore,dev'
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3